# ./run_pipeline.sh abatia
# ./run_pipeline.sh adrianopolis
# ./run_pipeline.sh agudosdosul
# ./run_pipeline.sh almirantetamandare
# ./run_pipeline.sh altamiradoparana
# ./run_pipeline.sh altonia
# ./run_pipeline.sh altoparana
# ./run_pipeline.sh altopiquiri
# ./run_pipeline.sh alvoradadosul
# ./run_pipeline.sh altoparaiso
# ./run_pipeline.sh amapora
# ./run_pipeline.sh ampere
# ./run_pipeline.sh anahy
# ./run_pipeline.sh andira

# ./run_pipeline.sh angulo
# ./run_pipeline.sh antonina
# ./run_pipeline.sh antonioolinto

# ./run_pipeline.sh apucarana
# ./run_pipeline.sh arapongas
# ./run_pipeline.sh arapoti

# ./run_pipeline.sh arapua
# ./run_pipeline.sh araruna
# ./run_pipeline.sh araucaria

# Executei as de cima ou estou rodando as de cima

# ./run_pipeline.sh ariranhadoivai
# ./run_pipeline.sh assai
# ./run_pipeline.sh assischateaubriand
# ./run_pipeline.sh astorga
# ./run_pipeline.sh atalaia
# ./run_pipeline.sh balsanova
# ./run_pipeline.sh bandeirantes
# ./run_pipeline.sh barbosaferraz
# ./run_pipeline.sh barracao
# ./run_pipeline.sh barradojacare
# ./run_pipeline.sh belavistadacaroba
# ./run_pipeline.sh belavistadoparaiso
# ./run_pipeline.sh bituruna
# ./run_pipeline.sh boaesperanca
# ./run_pipeline.sh boaesperancadoiguacu
# ./run_pipeline.sh boaventuradesaoroque
# ./run_pipeline.sh boavistadaaparecida
# ./run_pipeline.sh bocaiuvadosul
# ./run_pipeline.sh bomjesusdosul
# ./run_pipeline.sh bomsucesso
# ./run_pipeline.sh bomsucessodosul
# ./run_pipeline.sh borrazopolis
# ./run_pipeline.sh braganey
# ./run_pipeline.sh brasilandiaodosul
# ./run_pipeline.sh cafeara
# ./run_pipeline.sh cafelandia
# ./run_pipeline.sh cafezaldosul
# ./run_pipeline.sh california
# ./run_pipeline.sh cambara
# ./run_pipeline.sh cambe
# ./run_pipeline.sh cambira
# ./run_pipeline.sh campinadalagoa
# ./run_pipeline.sh campinadosimao
# ./run_pipeline.sh campinagrandedosul
# ./run_pipeline.sh campobonito
# ./run_pipeline.sh campodotenente
# ./run_pipeline.sh campolargo
# ./run_pipeline.sh campomagro
# ./run_pipeline.sh campomourao
# ./run_pipeline.sh candidodeabreu
# ./run_pipeline.sh candoi
# ./run_pipeline.sh cantagalo
# ./run_pipeline.sh capanema
# ./run_pipeline.sh capitolaeonidasmarques
# ./run_pipeline.sh carambei
# ./run_pipeline.sh carlopolis
# ./run_pipeline.sh cascavel
# ./run_pipeline.sh castro
# ./run_pipeline.sh catanduvas
# ./run_pipeline.sh centenariodosul
# ./run_pipeline.sh cerroazul
# ./run_pipeline.sh ceuazul
# ./run_pipeline.sh chopinzinho
# ./run_pipeline.sh cianorte
# ./run_pipeline.sh cidadegaucha
# ./run_pipeline.sh clevelandia
# ./run_pipeline.sh colombo
# ./run_pipeline.sh colorado
# ./run_pipeline.sh congonhinhas
# ./run_pipeline.sh conselheiromairinck
# ./run_pipeline.sh contenda
# ./run_pipeline.sh corbelia
# ./run_pipeline.sh cornelioprocopio
# ./run_pipeline.sh coroneldomingossoares
# ./run_pipeline.sh coronelvivida
# ./run_pipeline.sh corumbataidosul
# ./run_pipeline.sh cruzeirodoiguacu
# ./run_pipeline.sh cruzeirodooeste
# ./run_pipeline.sh cruzeirodosul
# ./run_pipeline.sh cruzmachado
# ./run_pipeline.sh cruzmaltina
# ./run_pipeline.sh curitiba
# ./run_pipeline.sh curiuva
# ./run_pipeline.sh diamantedoeste
# ./run_pipeline.sh diamantedonorte
# ./run_pipeline.sh diamantedosul
# ./run_pipeline.sh doisvizinhos
# ./run_pipeline.sh douradina
# ./run_pipeline.sh doutorcamargo
# ./run_pipeline.sh doutorulysses
# ./run_pipeline.sh eneasmarques
# ./run_pipeline.sh engenheirobeltrao
# ./run_pipeline.sh entreriosdooeste
# ./run_pipeline.sh esperancanova
# ./run_pipeline.sh espigaoaltodoiguacu
# ./run_pipeline.sh farol
# ./run_pipeline.sh faxinal
# ./run_pipeline.sh fazendariogrande
# ./run_pipeline.sh fenix
# ./run_pipeline.sh fernandespinheiro
# ./run_pipeline.sh figueira
# ./run_pipeline.sh florai
# ./run_pipeline.sh flordaserradosul
# ./run_pipeline.sh floresta
# ./run_pipeline.sh florestopolis
# ./run_pipeline.sh florida
# ./run_pipeline.sh formosadooeste
# ./run_pipeline.sh fozdoiguacu
# ./run_pipeline.sh fozdojordao
# ./run_pipeline.sh franciscoalves
# ./run_pipeline.sh franciscobeltrao
# ./run_pipeline.sh generalcarneiro
# ./run_pipeline.sh godoymoreira
# ./run_pipeline.sh goioere
# ./run_pipeline.sh goioxim
# ./run_pipeline.sh grandesrios
# ./run_pipeline.sh guaira
# ./run_pipeline.sh guairaca
# ./run_pipeline.sh guamiranga
# ./run_pipeline.sh guapirama
# ./run_pipeline.sh guaporema
# ./run_pipeline.sh guaraci
# ./run_pipeline.sh guaraniacu
# ./run_pipeline.sh guarapuava
# ./run_pipeline.sh guaraquecaba
# ./run_pipeline.sh guaratuba
# ./run_pipeline.sh honorioserpa
# ./run_pipeline.sh ibaiti
# ./run_pipeline.sh ibema
# ./run_pipeline.sh ibipora
# ./run_pipeline.sh icaraima
# ./run_pipeline.sh iguaracu
# ./run_pipeline.sh iguatu
# ./run_pipeline.sh imbau
# ./run_pipeline.sh imbituva
# ./run_pipeline.sh inaciomartins
# ./run_pipeline.sh inaja
# ./run_pipeline.sh indianopolis
# ./run_pipeline.sh ipiranga
# ./run_pipeline.sh ipora
# ./run_pipeline.sh iracemadooeste
# ./run_pipeline.sh irati
# ./run_pipeline.sh iretama
# ./run_pipeline.sh itaguaje
# ./run_pipeline.sh itaipulandia
# ./run_pipeline.sh itambaraca
# ./run_pipeline.sh itambe
# ./run_pipeline.sh itapejaradoeste
# ./run_pipeline.sh itaperucu
# ./run_pipeline.sh itaunadosul
# ./run_pipeline.sh ivai
# ./run_pipeline.sh ivaipora
# ./run_pipeline.sh ivate
# ./run_pipeline.sh ivatuba
# ./run_pipeline.sh jaboti
# ./run_pipeline.sh jacarezinho
# ./run_pipeline.sh jaguapita
# ./run_pipeline.sh jaguariaiva
# ./run_pipeline.sh jandaiadosul
# ./run_pipeline.sh janiopolis
# ./run_pipeline.sh japira
# ./run_pipeline.sh japura
# ./run_pipeline.sh jardimalegre
# ./run_pipeline.sh jardimolinda
# ./run_pipeline.sh jataizinho
# ./run_pipeline.sh jesuitas
# ./run_pipeline.sh joaquimtavora
# ./run_pipeline.sh jundiaidosul
# ./run_pipeline.sh juranda
# ./run_pipeline.sh jussara
# ./run_pipeline.sh kalore
# ./run_pipeline.sh lapa
# ./run_pipeline.sh laranjal
# ./run_pipeline.sh laranjeirasdosul
# ./run_pipeline.sh leopolis
# ./run_pipeline.sh lidianopolis
# ./run_pipeline.sh lindoeste
# ./run_pipeline.sh loanda
# ./run_pipeline.sh lobato
# ./run_pipeline.sh londrina
# ./run_pipeline.sh luiziana
# ./run_pipeline.sh lunardelli
# ./run_pipeline.sh lupionopolis
# ./run_pipeline.sh mallet
# ./run_pipeline.sh mambore
# ./run_pipeline.sh mandaguacu
# ./run_pipeline.sh mandaguari
# ./run_pipeline.sh mandirituba
# ./run_pipeline.sh manfrinopolis
# ./run_pipeline.sh mangueirinha
# ./run_pipeline.sh manoelribas
# ./run_pipeline.sh marechalcandidorondon
# ./run_pipeline.sh mariahelena
# ./run_pipeline.sh marialva
# ./run_pipeline.sh marilandiadosul
# ./run_pipeline.sh marilena
# ./run_pipeline.sh mariluz
# ./run_pipeline.sh maringa
# ./run_pipeline.sh mariopolis
# ./run_pipeline.sh maripa
# ./run_pipeline.sh marmeleiro
# ./run_pipeline.sh marquinho
# ./run_pipeline.sh marumbi
# ./run_pipeline.sh matelandia
# ./run_pipeline.sh matinhos
# ./run_pipeline.sh matorico
# ./run_pipeline.sh mauadaserra
# ./run_pipeline.sh medianeira
# ./run_pipeline.sh mercedes
# ./run_pipeline.sh mirador
# ./run_pipeline.sh miraselva
# ./run_pipeline.sh missal
# ./run_pipeline.sh moreirasales
# ./run_pipeline.sh morretes
# ./run_pipeline.sh munhozdemelo
# ./run_pipeline.sh nossasenhoradasgracas
# ./run_pipeline.sh novaaliancadoivai
# ./run_pipeline.sh novaamericadacolina
# ./run_pipeline.sh novaaurora
# ./run_pipeline.sh novacantu
# ./run_pipeline.sh novaesperanca
# ./run_pipeline.sh novaesperancadosudoeste
# ./run_pipeline.sh novafatima
# ./run_pipeline.sh novalaranjeiras
# ./run_pipeline.sh novalondrina
# ./run_pipeline.sh novaolimpia
# ./run_pipeline.sh novapratadoiguacu
# ./run_pipeline.sh novasantabarbara
# ./run_pipeline.sh novasantarosa
# ./run_pipeline.sh novatebas
# ./run_pipeline.sh novoitacolomi
# ./run_pipeline.sh ortigueira
# ./run_pipeline.sh ourizona
# ./run_pipeline.sh ouroverdedooeste
# ./run_pipeline.sh paicandu
# ./run_pipeline.sh palmas
# ./run_pipeline.sh palmeira
# ./run_pipeline.sh palmital
# ./run_pipeline.sh palotina
# ./run_pipeline.sh paraisodonorte
# ./run_pipeline.sh paranacity
# ./run_pipeline.sh paranagua
# ./run_pipeline.sh paranapoema
# ./run_pipeline.sh paranavai
# ./run_pipeline.sh patobragado
# ./run_pipeline.sh patobranco
# ./run_pipeline.sh paulafreitas
# ./run_pipeline.sh paulofrontin
# ./run_pipeline.sh peabiru
# ./run_pipeline.sh perobal
# ./run_pipeline.sh perola
# ./run_pipeline.sh peroladoeste
# ./run_pipeline.sh pien
# ./run_pipeline.sh pinhais
# ./run_pipeline.sh pinhalao
# ./run_pipeline.sh pinhaldesaobento
# ./run_pipeline.sh pinhao
# ./run_pipeline.sh piraidosul
# ./run_pipeline.sh piraquara
# ./run_pipeline.sh pitanga
# ./run_pipeline.sh pitangueiras
# ./run_pipeline.sh planaltinadoparana
# ./run_pipeline.sh planalto
# ./run_pipeline.sh pontagrossa
# ./run_pipeline.sh pontaldoparana
# ./run_pipeline.sh porecatu
# ./run_pipeline.sh portoamazonas
# ./run_pipeline.sh portobarreiro
# ./run_pipeline.sh portorico
# ./run_pipeline.sh portovitoria
# ./run_pipeline.sh pradoferreira
# ./run_pipeline.sh pranchita
# ./run_pipeline.sh presidentecastelobranco
# ./run_pipeline.sh primeirodemaio
# ./run_pipeline.sh prudentopolis
# ./run_pipeline.sh quartocentenario
# ./run_pipeline.sh quatigua
# ./run_pipeline.sh quatrobarras
# ./run_pipeline.sh quatropontes
# ./run_pipeline.sh quedasdoiguacu
# ./run_pipeline.sh querenciadonorte
# ./run_pipeline.sh quintadosol
# ./run_pipeline.sh quitandinha
# ./run_pipeline.sh ramilandia
# ./run_pipeline.sh ranchoalegre
# ./run_pipeline.sh ranchoalegredoeste
# ./run_pipeline.sh realeza
# ./run_pipeline.sh reboucas
# ./run_pipeline.sh renascenca
# ./run_pipeline.sh reserva
# ./run_pipeline.sh reservadoiguacu
# ./run_pipeline.sh ribeiraoclaro
# ./run_pipeline.sh ribeiraodopinhal
# ./run_pipeline.sh rioazul
# ./run_pipeline.sh riobom
# ./run_pipeline.sh riobonitodoiguacu
# ./run_pipeline.sh riobrancodoivai
# ./run_pipeline.sh riobrancodosul
# ./run_pipeline.sh rionegro
# ./run_pipeline.sh rolandia
# ./run_pipeline.sh roncador
# ./run_pipeline.sh rondon
# ./run_pipeline.sh rosariodoivai
# ./run_pipeline.sh sabaudia
# ./run_pipeline.sh salgadofilho
# ./run_pipeline.sh saltodoitarare
# ./run_pipeline.sh saltodolontra
# ./run_pipeline.sh santaamelia
# ./run_pipeline.sh santaceciliadopavao
# ./run_pipeline.sh santacruzdemontecastelo
# ./run_pipeline.sh santafe
# ./run_pipeline.sh santahelena
# ./run_pipeline.sh santaines
# ./run_pipeline.sh santaisabeldoivai
# ./run_pipeline.sh santaizabeldooeste
# ./run_pipeline.sh santalucia
# ./run_pipeline.sh santamariadooeste
# ./run_pipeline.sh santamariana
# ./run_pipeline.sh santamonica
# ./run_pipeline.sh santanadoitarare
# ./run_pipeline.sh santaterezadooeste
# ./run_pipeline.sh santaterezinhadeitaipu
# ./run_pipeline.sh santoantoniodaplatina
# ./run_pipeline.sh santoantoniodocaiua
# ./run_pipeline.sh santoantoniodoparaiso
# ./run_pipeline.sh santoantoniodosudoeste
# ./run_pipeline.sh santoinacio
# ./run_pipeline.sh saocarlosdoivai
# ./run_pipeline.sh saojeronimodaserra

# ./run_pipeline.sh saojoao
# ./run_pipeline.sh saojoaodocaiua
# ./run_pipeline.sh saojoaodoivai

# ./run_pipeline.sh saojoaodotriunfo
# ./run_pipeline.sh saojorgedoeste
# ./run_pipeline.sh saojorgedoivai

# ./run_pipeline.sh saojorgedopatrocinio
# ./run_pipeline.sh saojosedaboavista
# ./run_pipeline.sh saojosedaspalmeiras

# ./run_pipeline.sh saojosedospinhais
# ./run_pipeline.sh saomanoeldoparana
# ./run_pipeline.sh saomateusdosul

# ./run_pipeline.sh saomigueldoiguacu
# ./run_pipeline.sh saopedrodoiguacu
# ./run_pipeline.sh saopedrodoivai
# ./run_pipeline.sh saopedrodoparana
# ./run_pipeline.sh saosebastiaodaamoreira
# ./run_pipeline.sh saotome
# ./run_pipeline.sh sapopema
# ./run_pipeline.sh sarandi
# ./run_pipeline.sh saudadedoiguacu
# ./run_pipeline.sh senges
# ./run_pipeline.sh serranopolisdoiguacu
# ./run_pipeline.sh sertaneja

# ./run_pipeline.sh sertanopolis
# ./run_pipeline.sh siqueiracampos
# ./run_pipeline.sh sulina

# ./run_pipeline.sh tamarana
# ./run_pipeline.sh tamboara
# ./run_pipeline.sh tapejara

# ./run_pipeline.sh tapira
# ./run_pipeline.sh teixeirasoares
# ./run_pipeline.sh telemacoborba
# ./run_pipeline.sh terraboa
# ./run_pipeline.sh terrarica
# ./run_pipeline.sh terraroxa

# ./run_pipeline.sh tibagi
# ./run_pipeline.sh tijucasdosul
# ./run_pipeline.sh toledo

# ./run_pipeline.sh tomazina
# ./run_pipeline.sh tresbarrasdoparana
# ./run_pipeline.sh tunasdoparana

# ./run_pipeline.sh tuneirasdooeste
# ./run_pipeline.sh tupassi
# ./run_pipeline.sh turvo

# ./run_pipeline.sh ubirata
# ./run_pipeline.sh umuarama
# ./run_pipeline.sh uniaodavitoria

# ./run_pipeline.sh uniflor
# ./run_pipeline.sh urai
# ./run_pipeline.sh ventania
# ./run_pipeline.sh veracruzdooeste
# ./run_pipeline.sh vere
# ./run_pipeline.sh virmond
# ./run_pipeline.sh vitorino
# ./run_pipeline.sh wenceslaubraz
# ./run_pipeline.sh xambre
